# Get your api key at https://www.appcanary.com/settings
api_key: ""

# Name your server (optional)
#server_name: ""

# add your gemfiles by uncommenting these lines:

#watchers:
#- path: "/var/www/someapp/current/Gemfile.lock"

